CREATE DATABASE IF NOT EXISTS logs;
USE logs;

CREATE TABLE IF NOT EXISTS log_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  resourceId VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  traceId VARCHAR(255) NOT NULL,
  spanId VARCHAR(255) NOT NULL,
  commit VARCHAR(255) NOT NULL,
  parentResourceId VARCHAR(255)
);
